name: Build and Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  industrial_ci:
    strategy:
      fail-fast: false
      matrix:
        env:
          - ROS_DISTRO: jazzy
          - ROS_DISTRO: humble
          - ROS_DISTRO: rolling

    env:
      ROS_REPO: main

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{ matrix.env }}
